image: node:18.14.2

definitions:
  services:
    docker:
      memory: 6000
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
          - sonar
          - docker # used by sonar pipes
        size: 2x # needed for additional memory requirements
        clone:
          depth: full # SonarCloud scanner needs the full history to assign issues properly
        script:
          - git submodule update --init --recursive
          - cd org.knime.js.pagebuilder
          - npm ci
          - npm run ci:lint-format
          - npm run coverage
          - pipe: sonarsource/sonarcloud-scan:2.0.0
            variables:
              SONAR_SCANNER_OPTS: -Xmx4G
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
          - npm run build
          - npm run audit
        artifacts:
          - org.knime.js.pagebuilder/dist/**

pipelines:
  pull-requests:
    '**':
      - step: *lint-test-build
  branches:
    '{master,releases/*}':
      - step: *lint-test-build